# Generated by Django 4.2.1 on 2023-06-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="selected",
            field=models.BooleanField(default=False),
        ),
    ]
